### ISSUE TITLE
datamigration  error at "Url Rewrite" (Mismatch of entities in the document: url_rewrite,Error occurred. Rollback.,Please fix errors and run Migration Tool again)

### ISSUE THREAD

**Issue by anoopaugustin** [magento/data-migration-tool#100]
[2016-06-24 06:56:42][INFO][mode: data][stage: data migration][step: Url Rewrite Step]: started
[2016-06-24 06:56:59][INFO][mode: data][stage: volume check][step: Url Rewrite Step]: started
[2016-06-24 06:57:00][ERROR]: Mismatch of entities in the document: url_rewrite
[2016-06-24 06:57:00][INFO][mode: data][stage: volume check][step: Url Rewrite Step]: Error occurred. Rollback.
[2016-06-24 06:57:00][INFO][mode: data][stage: volume check][step: Url Rewrite Step]: Url Rewrite Step: rollback
[2016-06-24 06:57:00][INFO][mode: data][stage: volume check][step: Url Rewrite Step]: Please fix errors and run Migration Tool again
I got this error when migrating data  from magento 1.9.2.4 to 2.0.2 using datamigrationtool 2.0.2
can anyone help me to solve this issue?

**Comment by victor-v-rad** [comment]
Hi @anoopaugustin 
I encountered such error before. With new release of the tool it should be fixed. Please follow up on updates

**Comment by victor-v-rad** [comment]
@anoopaugustin 
The issue was fixed in the latest release of the tool 2.1.1
Please recheck

**Comment by ravinders-121** [comment]
Hi @victor-v-rad 

I am migrating from EE 1.11.2.0 to EE 2.1.3 using migration tool 2.1.3 but still facing same error. Any thoughts on this?

**Comment by dfelton** [comment]
@ravinders-121 this error is thrown when the total number of collected URL Rewrites & Redirects in the Magento 1 database does not match the total number inserted into the Magento 2 database.

Thrown in here depending on which class is being used:
- [Version11300to2000](https://github.com/magento/data-migration-tool/blob/master/src/Migration/Step/UrlRewrite/Version11300to2000.php#L533)
- [Version11410to2000](https://github.com/magento/data-migration-tool/blob/master/src/Migration/Step/UrlRewrite/Version11410to2000.php#L538)
- [Version191to2000](https://github.com/magento/data-migration-tool/blob/master/src/Migration/Step/UrlRewrite/Version191to2000.php#L257)

Have you modified the original file at all?

**Comment by ravinders-121** [comment]
@dfelton yes I have observed that it is being caused by a mismatch between URL rewrite count between M1 and M2 databases but couldn't found a reason for this.

I haven't modified any of the three files listed by you but I have debugged this and found that it's getting triggered from file 

Version191to2000

**Comment by dfelton** [comment]
@ravinders-121 Sorry I haven't worked with that version of the URL Rewrite migration class yet, and it differs significantly from the EE versions. 

One recommendation may be to revise the volume() method to output additional information about the mismatch. You could add logic to select `request_path` from the `SOURCE` table, and `request_path` from the `DESTINATION` table, and compare the differences.

**Comment by Schrank** [comment]
I have the same problem. On my side all cms-page rewrites are missing.

I checked in the code how much are missing (in my case 1) and added a +1 to fix the if. Missing one rewrite is not worth debugging... But who knows how much are missing in your™ (future reader) case :-/

**Comment by andy-igoo** [comment]
@Schrank I'm also getting a difference of 1
