### ISSUE TITLE
No route page content display on every product page

### ISSUE THREAD

**Issue by Yogesh7989** [magento/data-migration-tool#215]
Hello ,

I have done migration from magento 1.9.3.1 to 2.1.3 by migration tool 2.1.3. Every things is working except one thing.

Every product page called first no-route page after product details is displayed. both page (404page + product detail )content display together.  

There is in console i have seen first request is pass with product url like : "**Network Error: 404 Not Found - http://localhost/georeef/lps-coral/fire-ice.html**" , after that all request passed.

So there is additional request send on every product page after migration this is create problem. you can take reference this thread [http://magento.stackexchange.com/questions/153512/after-migration-no-route-page-content-display-on-every-product-page].
![error](https://cloud.githubusercontent.com/assets/7812808/21716811/f31cc0ea-d432-11e6-94d9-39c4d9f69e69.png)
![404 not found 1 georeef](https://cloud.githubusercontent.com/assets/7812808/21716816/f93116e8-d432-11e6-89b7-81b6968893a3.png)

Any one have idea why happen this ?

Thanks
Yogesh

**Comment by victor-v-rad** [comment]
Hi @Yogesh7989 
It might be Widget or CMS Block which is not migrated properly. Please check it

**Comment by Yogesh7989** [comment]
Hello @victor-v-rad ,

I have save product from admin panel and error has been resolved. very surprising but issue has been solved is more important.

Thanks
Yogesh

**Comment by victor-v-rad** [comment]
Glad to know your issue is solved. However the root cause has not been identified.

**Comment by hardikmsp** [comment]
Hi, i have no idea why this ticket is closed because the issue is still not solved. I am facing the same issue after migrating from Magento1.x to Magento2.x. After i save product manually from the admin, it works very well.

Can anyone please help me in this.
