### ISSUE TITLE
Delta Migration Error: Deltalog for customer_entity

### ISSUE THREAD

**Issue by joshuacalebm** [magento/data-migration-tool#279]
Ready to go live with m2 on a staging server after successfully migrating a few weeks ago from 1.7.0.2.

Trying to update with new customers and recent orders in the past few weeks since migration. 

After trying the _migrate:delta_ command, I'm getting the Error: **Deltalog for customer_entity is not installed.** 

The source mysql db, the destination db, and the delta db are all providing user with complete privileges. 

I understand this has previously been brought up as an issue but none of the responses had a clear solution to this issue.

**Comment by victor-v-rad** [comment]
Hi @joshuacalebm 

Can you find m2_cl_* tables in your Magento 1 DB? Does m2_cl_customer_entity table exists?

**Comment by joshuacalebm** [comment]
Hi. @victor-v-rad thanks for the reply. No the tables don't exist in the original m1 db I used for migration, but I'm actually trying to use a newer version of the original db I imported into the staging server since the hosting co won't allow remote db access. I read somewhere one would have to create these tables?

**Comment by victor-v-rad** [comment]
Hi @joshuacalebm 

The tool creates these tables when `php bin/magento migrate:data` is run. It is used in 'delta mode' when you run `php bin/magento migrate:delta`. I believe the tool should notify a user that delta tables could not have been created. Internal ticket MAGETWO-67773 to implement it if possible

**Comment by webkulabhi** [comment]
Hi @victor-v-rad 
In which case tool did not create m2_cl_* tables in magento1 database? both database assigned to same user.

**Comment by victor-v-rad** [comment]
@webkulabhi 
No privileges can be the cause. Check for errors in logs. Connect with this user to the MySQL and try to create some table manually.

**Comment by webkulabhi** [comment]
@victor-v-rad 
user have already permission for create table.
may be some issues with 2.1.5 version. I tried with 2.1.6 and its working perfectly.
Thanks for your response.

**Comment by victor-v-rad** [comment]
Fixed

**Comment by MohanaKrishnan7** [comment]
@victor-v-rad It is not fixed !. @webkulabhi saying that "It is not working in 2.1.5." and I'm also facing the same error "Deltalog for customer_entity is not installed" in 2.2.4.

**Comment by Rudoslav** [comment]
So I found out what was the issue.

When you try to run migrate:delta without running migrate:data before basically. The problem is that those delta log tables (m2_cl_*) are missing.

**Comment by sohrobdevise** [comment]
@MohanaKrishnan7 @Rudoslav 
Have you been able to find a solution for this? I am on version 2.2.5 and cannot find a solution.
Anything would be appreciated!

**Comment by Rudoslav** [comment]
@sohrobdevise

See my last comment above.
Check if your source (Magento 1) database does have delta/change list tables created.
Delta tables should have names starting with m2_cl_*.

**Comment by MohanaKrishnan7** [comment]
> @MohanaKrishnan7 @Rudoslav
> Have you been able to find a solution for this? I am on version 2.2.5 and cannot find a solution.
> Anything would be appreciated!

@sohrobdevise 

As @Rudoslav said, check whether you have m2_cl_* tables in your Magento 1 database in which you are running the DELTA migration.

If you don't find the tables. then you are running the DELTA migration in a different Magento 1 database and you have run the DATA migration in another Magento 1 database. Find the database in which you run the DATA migration and run the DELTA migration again.

If you are getting any other issues, take a fresh copy of your Magento 1 database and delete all the m2_cl_* tables. Install a fresh Magento 2 and try all the migration steps.

Thanks and Regards
MohanaKrishnan.
