### ISSUE TITLE
url_rewrite duplicates

### ISSUE THREAD

**Issue by redboxmarcins** [magento/data-migration-tool#81]
While migrating from CE 1.7.0.2 to EE 2.0.4 url rewrites are migrated from core_url_rewrite to url_rewrite table, but EE 2.0.4 require (same as 1.13EE and 1.8CE) that url keys must be unique
so saving category or product is not possible after migration

So far using https://gist.github.com/Vinai/5451584 to clear data before doing migration, but I believe that should be handled by migration tool

**Comment by ilol** [comment]
Thank you, @redboxmarcins, will discuss this with development team @yaronish @victor-v-rad

**Comment by victor-v-rad** [comment]
> url keys must be unique
Yes, but request_path + store_id must be unique in Magento 2. 

> so saving category or product is not possible after migration
I have not encountered such issue after migration so far. But I will investigate this case more thoroughly.

**Comment by redboxmarcins** [comment]
@victor-v-rad did you try to migrate data where url keys are not unique - f.e. from version before 1.8.x ?

**Comment by ilol** [comment]
MAGETWO-52505

**Comment by craigcarnell** [comment]
@ilol Any updates on this issue? This is the last issue preventing me from handing over a decent M1 database -> M2

**Comment by craigcarnell** [comment]
Even with running: https://gist.github.com/Vinai/5451584 I still get:
                                                                                                                                                                
  [PDOException]                                                                                                                                                
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'upright-vacuum-cleaners/swift-upright-22' for key 'URL_REWRITE_REQUEST_PATH_STORE_ID'

**Comment by victor-v-rad** [comment]
@redboxmarcins 
The issue was fixed in the latest release of the tool 2.1.1
Please recheck

**Comment by victor-v-rad** [comment]
I am closing the issue. Feel free to reopen if it is still actual

**Comment by craigcarnell** [comment]
@victor-v-rad I just tested this with 2.1.1 and I still get it

**Comment by victor-v-rad** [comment]
The easiest way might be to send us the DB dump (cleaned from passwords). Here https://github.com/victor-v-rad you can find my email.

**Comment by victor-v-rad** [comment]
internal ticket MAGETWO-59233 to fix the issue

**Comment by alessandrozucca** [comment]
I'm having similar issues, i'll send you a private email.

**Comment by victor-v-rad** [comment]
@craigcarnell @alessandrozucca 
Guys try out the solution from [the commit](https://github.com/magento-nord/data-migration-tool/commit/963003c3c8ac863352e16d69c6f82992a2a22559)

**Comment by alessandrozucca** [comment]
I've found a workaround for this. I'm removing the index `URL_REWRITE_REQUEST_PATH_STORE_ID` before I run the migration. If you do this all the values get added.

Then, you need to check the duplicates, I've run a query grouping by request_path and store_id where the count(*) was > 1. In my case I've found around 56 duplicates. 
Some of the duplicates where NULL request_paths, some where request_path with a length > 255 chars which got truncated as they were too long, and one was a short request_path (10 char) that for some reason was a duplicate.

In my situation I could just remove all duplicates as all this urls were belonging to disabled stores, then I have re-added the `URL_REWRITE_REQUEST_PATH_STORE_ID` index and all sorted!

**Comment by craigcarnell** [comment]
@victor-v-rad I tried out your changes and got much, much further but it stopped here:

```
[2016-10-10 09:22:17][INFO][mode: data][stage: data migration][step: Url Rewrite Step]: started
98% [===========================>] Remaining Time: 1 sec  

                                                                                                                                        
  [PDOException]                                                                                                                        
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 's2s-1-steamer -3' for key 'URL_REWRITE_REQUEST_PATH_STORE_ID' 
```

**Comment by craigcarnell** [comment]
@victor-v-rad any update on this?

**Comment by victor-v-rad** [comment]
I have migrated magento_prod_2016-12-02.sql you send me and not found such error "Integrity constraint violation". With auto_resolve_urlrewrite_duplicates=1 migration completed without errors
